/* ============ 데이터 ============ */
const CATS = {
  found:"기초 개념",
  learn:"학습 방식",
  net:"신경망 구조",
  train:"모델 훈련",
  eval:"성능 평가",
  prep:"데이터 전처리",
  nlp:"자연어 처리 (NLP)",
  vision:"컴퓨터 비전",
  rl:"강화 학습",
  tech:"학습 기법",
  infra:"인프라 · 도구",
  ethics:"AI 윤리",
  gen:"생성형 AI · LLM",
  coreml:"핵심 ML 알고리즘",
  ops:"MLOps · 운영",
  biz:"AI 비즈니스"
};

const TERMS = [
  ["인공지능","Artificial Intelligence (AI)","사람처럼 생각하고 배우고 문제를 해결하는 컴퓨터 기술.","found"],
  ["머신러닝","Machine Learning","AI의 한 분야로, 컴퓨터가 데이터를 통해 스스로 학습하는 기술.","found"],
  ["딥러닝","Deep Learning","머신러닝의 한 종류로, 인공 신경망을 사용해 더 복잡한 문제를 해결.","found"],
  ["알고리즘","Algorithm","문제를 해결하기 위한 단계별 절차나 방법. AI의 핵심.","found"],
  ["데이터","Data","AI가 학습하고 분석하는 데 사용하는 정보. 텍스트·이미지·소리 등.","found"],
  ["빅데이터","Big Data","엄청나게 큰 규모의 데이터. AI는 이를 활용해 학습한다.","found"],
  ["트레이닝","Training","AI 모델이 데이터를 통해 학습하는 과정. 일종의 공부.","found"],
  ["모델","Model","AI가 학습한 결과를 나타내는 것. 쉽게 말해 AI의 지식 창고.","found"],
  ["피처 (특징)","Feature","데이터에서 AI가 학습하는 중요한 요소. (예: 고양이 인식의 수염·귀)","found"],
  ["파라미터 (매개변수)","Parameter","AI 모델 내부에서 학습되는 값. 모델 성능에 영향을 미친다.","learn"],
  ["지도 학습","Supervised Learning","정답이 있는 데이터를 통해 학습하는 방식.","learn"],
  ["비지도 학습","Unsupervised Learning","정답 없이 데이터 자체의 패턴을 학습하는 방식.","learn"],
  ["신경망","Neural Network","AI의 핵심 구조로 인간의 뇌 신경망을 모방했다.","net"],
  ["심층 신경망","Deep Neural Network","여러 층으로 구성된 신경망으로 딥러닝에 사용된다.","net"],
  ["노드 (뉴런)","Node / Neuron","신경망의 기본 구성 요소로 정보를 처리한다.","net"],
  ["레이어 (층)","Layer","신경망 내에서 노드들이 모여 있는 층.","net"],
  ["활성화 함수","Activation Function","노드의 출력을 결정하는 함수.","net"],
  ["가중치","Weight","신경망 연결의 강도를 나타내는 값. 학습을 통해 조정된다.","net"],
  ["편향","Bias","신경망의 학습을 돕는 값.","net"],
  ["에포크","Epoch","전체 데이터를 한 번 학습하는 단위.","train"],
  ["배치 사이즈","Batch Size","한 번의 학습에 사용되는 데이터의 양.","train"],
  ["이터레이션 (반복)","Iteration","한 번의 에포크 내에서 학습이 반복되는 횟수.","train"],
  ["손실 함수","Loss Function","모델의 예측과 실제 값의 차이를 측정하는 함수.","train"],
  ["옵티마이저 (최적화)","Optimizer","손실을 최소화하기 위해 모델을 튜닝하는 알고리즘.","train"],
  ["경사 하강법","Gradient Descent","옵티마이저가 사용하는 방법 중 하나.","train"],
  ["학습률","Learning Rate","모델 학습 속도를 조절하는 값.","train"],
  ["과적합","Overfitting","훈련 데이터에 너무 맞춰져 새로운 데이터 예측 능력이 떨어지는 현상.","train"],
  ["과소적합","Underfitting","모델이 훈련 데이터조차 제대로 학습하지 못하는 현상.","train"],
  ["검증 세트","Validation Set","학습 중 모델의 성능을 평가하기 위해 사용되는 데이터 세트.","eval"],
  ["테스트 세트","Test Set","최종 모델의 성능을 평가하기 위해 사용되는 데이터 세트.","eval"],
  ["정확도","Accuracy","모델의 예측이 얼마나 정확한지를 나타내는 지표.","eval"],
  ["정밀도","Precision","모델이 긍정으로 예측한 것 중 실제로 긍정인 비율.","eval"],
  ["재현율","Recall","실제 긍정인 것 중 모델이 긍정으로 예측한 비율.","eval"],
  ["F1 점수","F1 Score","정밀도와 재현율의 조화 평균.","eval"],
  ["혼동 행렬","Confusion Matrix","모델의 예측 결과를 시각적으로 보여주는 표.","eval"],
  ["ROC 곡선","ROC Curve","모델의 성능을 시각적으로 평가하는 도구.","eval"],
  ["AUC","Area Under the Curve","ROC 곡선 아래의 면적을 의미하며 모델 성능을 나타낸다.","eval"],
  ["편향-분산 트레이드오프","Bias-Variance Tradeoff","모델의 편향과 분산 사이의 관계를 나타낸다.","eval"],
  ["데이터 전처리","Data Preprocessing","데이터를 학습에 적합한 형태로 변환하는 과정.","prep"],
  ["데이터 정제","Data Cleaning","결측치·이상치 등을 처리하여 데이터를 깨끗하게 만드는 과정.","prep"],
  ["특징 스케일링","Feature Scaling","특징 값의 범위를 조정하여 학습 효율을 높이는 방법.","prep"],
  ["정규화","Normalization","데이터를 특정 범위로 변환하는 방법.","prep"],
  ["표준화","Standardization","데이터의 평균을 0, 표준편차를 1로 변환하는 방법.","prep"],
  ["원-핫 인코딩","One-Hot Encoding","범주형 데이터를 수치 데이터로 변환하는 방법.","prep"],
  ["자연어 처리","Natural Language Processing (NLP)","AI가 인간의 언어를 이해하고 처리하는 기술.","nlp"],
  ["텍스트 분류","Text Classification","텍스트를 특정 카테고리로 분류하는 작업.","nlp"],
  ["감성 분석","Sentiment Analysis","텍스트의 긍정·부정을 판단하는 기술.","nlp"],
  ["개체명 인식","Named Entity Recognition","텍스트에서 사람·장소·조직 등의 정보를 인식하는 기술.","nlp"],
  ["기계 번역","Machine Translation","AI가 자동으로 언어를 번역하는 기술.","nlp"],
  ["챗봇","Chatbot","AI 기반의 대화형 프로그램.","nlp"],
  ["음성 인식","Speech Recognition","음성을 텍스트로 변환하는 기술.","nlp"],
  ["텍스트 음성 변환","Text-to-Speech (TTS)","텍스트를 음성으로 변환하는 기술.","nlp"],
  ["컴퓨터 비전","Computer Vision","AI가 이미지를 인식하고 분석하는 기술.","vision"],
  ["이미지 분류","Image Classification","이미지를 특정 카테고리로 분류하는 작업.","vision"],
  ["객체 감지","Object Detection","이미지 내 객체의 위치와 종류를 파악하는 기술.","vision"],
  ["이미지 분할","Image Segmentation","이미지를 픽셀 단위로 분할하여 객체를 인식하는 기술.","vision"],
  ["생성적 적대 신경망","Generative Adversarial Network (GAN)","이미지 생성 등에 사용되는 기술.","vision"],
  ["강화 학습","Reinforcement Learning","보상을 통해, 환경과 상호작용하며 학습하는 방식.","rl"],
  ["에이전트","Agent","강화 학습에서 학습 주체를 의미한다.","rl"],
  ["환경","Environment","에이전트가 상호작용하는 외부 환경.","rl"],
  ["상태","State","에이전트가 현재 환경을 인식하는 정보.","rl"],
  ["액션 (행동)","Action","에이전트가 환경에 대해 수행하는 동작.","rl"],
  ["보상","Reward","에이전트의 행동에 대한 긍정적 또는 부정적 피드백.","rl"],
  ["정책","Policy","에이전트가 어떤 행동을 할지 결정하는 전략.","rl"],
  ["가치 함수","Value Function","특정 상태에서 얻을 수 있는 예상 보상을 추정하는 함수.","rl"],
  ["Q-러닝","Q-Learning","강화 학습 알고리즘 중 하나.","rl"],
  ["심층 Q-네트워크","Deep Q-Network (DQN)","딥러닝을 활용한 강화 학습 알고리즘.","rl"],
  ["전이 학습","Transfer Learning","기존에 학습된 모델을 새로운 문제에 적용하는 기술.","tech"],
  ["미세 조정","Fine-tuning","전이 학습에서 기존 모델을 새 데이터에 맞게 추가 학습하는 과정.","tech"],
  ["앙상블 학습","Ensemble Learning","여러 모델의 예측을 결합하여 성능을 향상시키는 방법.","tech"],
  ["배깅","Bagging","앙상블 학습 기법 중 하나.","tech"],
  ["부스팅","Boosting","앙상블 학습 기법 중 하나.","tech"],
  ["그래디언트 부스팅","Gradient Boosting","부스팅 기법의 일종.","tech"],
  ["XGBoost","XGBoost","그래디언트 부스팅의 한 종류로 뛰어난 성능을 자랑한다.","tech"],
  ["데이터 마이닝","Data Mining","데이터에서 유용한 정보를 추출하는 과정.","tech"],
  ["군집화","Clustering","데이터를 유사한 그룹으로 묶는 기술.","tech"],
  ["이상 감지","Anomaly Detection","정상 데이터와 다른 이상 데이터를 찾아내는 기술.","tech"],
  ["추천 시스템","Recommendation System","사용자에게 상품·콘텐츠 등을 추천하는 시스템.","tech"],
  ["A/B 테스팅","A/B Testing","둘 이상의 버전을 비교하여 어떤 것이 더 효과적인지 평가하는 방법.","tech"],
  ["클라우드 컴퓨팅","Cloud Computing","인터넷을 통해 컴퓨팅 자원을 사용하는 방식.","infra"],
  ["GPU","Graphics Processing Unit","AI 학습에 사용되는 고성능 연산 장치 (그래픽 처리 장치).","infra"],
  ["TPU","Tensor Processing Unit","구글에서 개발한 AI 전용 프로세서 (텐서 처리 장치).","infra"],
  ["엣지 컴퓨팅","Edge Computing","데이터를 생성하는 기기 가까이에서 처리하는 방식.","infra"],
  ["API","Application Programming Interface","다른 프로그램과 데이터를 주고받기 위한 인터페이스.","infra"],
  ["SDK","Software Development Kit","소프트웨어 개발에 필요한 도구·라이브러리 등을 묶어 놓은 것.","infra"],
  ["오픈소스","Open Source","누구나 자유롭게 사용하고 수정할 수 있는 소프트웨어.","infra"],
  ["프레임워크","Framework","소프트웨어 개발을 위한 기본적인 틀을 제공한다.","infra"],
  ["텐서플로우","TensorFlow","구글에서 개발한 딥러닝 프레임워크.","infra"],
  ["파이토치","PyTorch","페이스북에서 개발한 딥러닝 프레임워크.","infra"],
  ["케라스","Keras","딥러닝 모델을 쉽게 만들 수 있도록 도와주는 API.","infra"],
  ["사이킷런","Scikit-learn","머신러닝 모델을 쉽게 구현할 수 있는 라이브러리.","infra"],
  ["주피터 노트북","Jupyter Notebook","코드 실행·시각화 등을 할 수 있는 개발 환경.","infra"],
  ["배포","Deployment","AI 모델을 실제 서비스에 적용하는 과정.","infra"],
  ["확장성","Scalability","시스템이 증가하는 요구에 맞춰 얼마나 쉽게 확장될 수 있는지를 나타낸다.","infra"],
  ["설명 가능한 AI","Explainable AI (XAI)","AI 모델의 의사결정 과정을 설명하는 기술.","ethics"],
  ["공정성","Fairness","AI 모델이 모든 집단에게 공정하게 적용될 수 있는지를 나타낸다.","ethics"],
  ["윤리","Ethics","AI 개발 및 사용에 있어서 지켜야 할 윤리적 가치.","ethics"],
  ["거대 언어 모델","Large Language Model (LLM)","방대한 텍스트로 학습해 사람처럼 글을 이해하고 생성하는 초대형 AI 모델.","gen"],
  ["파운데이션 모델","Foundation Model","대규모 데이터로 사전학습되어 다양한 작업에 응용되는 범용 기반 모델.","gen"],
  ["트랜스포머","Transformer","어텐션을 기반으로 한 구조로, 현대 LLM의 토대가 된 신경망 아키텍처.","gen"],
  ["어텐션 메커니즘","Attention Mechanism","입력에서 중요한 부분에 가중치를 두어 집중하게 하는 기법.","gen"],
  ["토큰","Token","모델이 처리하는 텍스트의 최소 단위로, 단어나 부분 단어를 말합니다.","gen"],
  ["토크나이저","Tokenizer","문장을 토큰으로 쪼개어 모델 입력으로 바꿔주는 도구.","gen"],
  ["임베딩","Embedding","단어나 문장을 의미를 담은 숫자 벡터로 표현한 것.","gen"],
  ["프롬프트","Prompt","AI에게 작업을 지시하기 위해 입력하는 명령이나 질문.","gen"],
  ["프롬프트 엔지니어링","Prompt Engineering","원하는 답을 얻도록 프롬프트를 설계하고 다듬는 기술.","gen"],
  ["컨텍스트 윈도우","Context Window","모델이 한 번에 참고할 수 있는 입력 토큰의 최대 길이.","gen"],
  ["환각","Hallucination","모델이 사실이 아닌 내용을 그럴듯하게 지어내는 현상.","gen"],
  ["검색 증강 생성","Retrieval-Augmented Generation (RAG)","외부 문서를 검색해 근거로 삼아 답을 생성하는 기법.","gen"],
  ["벡터 데이터베이스","Vector Database","임베딩 벡터를 저장하고 검색해 의미 기반 검색을 지원하는 데이터베이스.","gen"],
  ["시맨틱 검색","Semantic Search","키워드가 아니라 의미의 유사도로 정보를 찾는 검색.","gen"],
  ["제로샷 학습","Zero-shot Learning","예시 없이 지시만으로 새로운 작업을 수행하는 능력.","gen"],
  ["퓨샷 학습","Few-shot Learning","소수의 예시만 보고 작업을 수행하는 능력.","gen"],
  ["인컨텍스트 러닝","In-context Learning","프롬프트 안의 예시로 즉석에서 학습하듯 답하는 방식.","gen"],
  ["인간 피드백 강화학습","RLHF","사람의 피드백을 보상으로 삼아 모델을 사람 의도에 맞게 다듬는 학습법.","gen"],
  ["정렬","Alignment","모델의 행동을 인간의 의도와 가치에 맞추는 것.","gen"],
  ["멀티모달","Multimodal","텍스트·이미지·음성 등 여러 형태의 데이터를 함께 다루는 AI.","gen"],
  ["디퓨전 모델","Diffusion Model","노이즈를 점진적으로 제거하며 이미지를 생성하는 모델.","gen"],
  ["추론","Inference","학습이 끝난 모델로 실제 예측이나 생성을 수행하는 단계.","gen"],
  ["양자화","Quantization","모델 수치를 저정밀도로 줄여 속도와 용량을 개선하는 경량화 기법.","gen"],
  ["지식 증류","Knowledge Distillation","큰 모델의 지식을 작은 모델로 옮겨 가볍게 만드는 기법.","gen"],
  ["AI 에이전트","AI Agent","스스로 계획을 세우고 도구를 사용해 목표를 수행하는 자율 AI.","gen"],
  ["회귀","Regression","가격·온도처럼 연속적인 수치를 예측하는 문제나 기법.","coreml"],
  ["분류","Classification","데이터를 미리 정한 범주로 나누는 문제나 기법.","coreml"],
  ["선형 회귀","Linear Regression","직선 관계로 값을 예측하는 가장 기본적인 회귀.","coreml"],
  ["로지스틱 회귀","Logistic Regression","확률을 이용해 이진 분류를 수행하는 기법.","coreml"],
  ["의사결정 나무","Decision Tree","질문을 분기하며 결정을 내리는 트리 형태의 모델.","coreml"],
  ["랜덤 포레스트","Random Forest","여러 결정나무를 결합한 앙상블 분류·회귀 모델.","coreml"],
  ["서포트 벡터 머신","Support Vector Machine (SVM)","경계를 최대 마진으로 나누어 분류하는 기법.","coreml"],
  ["k-최근접 이웃","k-Nearest Neighbors (k-NN)","가까운 이웃 데이터를 참고해 분류·예측하는 단순한 기법.","coreml"],
  ["k-평균 군집화","K-means Clustering","데이터를 k개의 그룹으로 나누는 대표적 군집 알고리즘.","coreml"],
  ["나이브 베이즈","Naive Bayes","베이즈 정리를 이용한 단순하고 빠른 분류기.","coreml"],
  ["차원 축소","Dimensionality Reduction","특징의 수를 줄여 핵심 정보만 남기는 기법.","coreml"],
  ["주성분 분석","Principal Component Analysis (PCA)","분산이 큰 축으로 차원을 줄이는 대표적인 기법.","coreml"],
  ["하이퍼파라미터","Hyperparameter","학습 전에 사람이 직접 설정하는 모델 설정값.","coreml"],
  ["교차 검증","Cross-validation","데이터를 나눠 번갈아 검증하며 일반화 성능을 측정하는 방법.","coreml"],
  ["정칙화","Regularization","과적합을 막기 위해 모델 복잡도에 패널티를 주는 기법.","coreml"],
  ["드롭아웃","Dropout","학습 중 일부 뉴런을 무작위로 꺼서 과적합을 줄이는 기법.","coreml"],
  ["배치 정규화","Batch Normalization","각 층의 입력 분포를 정규화해 학습을 안정시키고 가속하는 기법.","coreml"],
  ["그래디언트 소실","Vanishing Gradient","층이 깊어질수록 기울기가 사라져 학습이 잘 안 되는 문제.","coreml"],
  ["합성곱 신경망","Convolutional Neural Network (CNN)","이미지 처리에 강점을 가진 신경망 구조.","coreml"],
  ["순환 신경망","Recurrent Neural Network (RNN)","문장·시계열처럼 순서가 있는 데이터를 다루는 신경망.","coreml"],
  ["MLOps","MLOps","머신러닝 모델의 개발·배포·운영을 자동화하고 관리하는 방식.","ops"],
  ["모델 드리프트","Model Drift","시간이 지나며 모델의 성능이 점차 떨어지는 현상.","ops"],
  ["데이터 드리프트","Data Drift","입력 데이터의 분포가 학습 때와 달라지는 현상.","ops"],
  ["피처 스토어","Feature Store","학습과 서비스에서 재사용할 특징을 저장·관리하는 시스템.","ops"],
  ["모델 서빙","Model Serving","학습된 모델을 실제 요청에 응답하도록 제공하는 것.","ops"],
  ["파이프라인","Pipeline","데이터 수집부터 학습·배포까지 연결한 자동화 흐름.","ops"],
  ["컨테이너","Container","앱과 실행 환경을 묶어 어디서나 똑같이 실행하는 기술.","ops"],
  ["데이터 레이크","Data Lake","원천 데이터를 형태 그대로 대규모로 저장하는 저장소.","ops"],
  ["데이터 파이프라인","Data Pipeline","데이터를 수집·변환·이동시키는 처리 경로.","ops"],
  ["모니터링","Monitoring","운영 중인 모델과 시스템의 상태·성능을 지속적으로 관찰하는 것.","ops"],
  ["생성형 AI","Generative AI","글·이미지·코드 등 새로운 콘텐츠를 만들어내는 AI.","biz"],
  ["디지털 트랜스포메이션","Digital Transformation","디지털 기술로 업무와 사업 방식을 근본적으로 혁신하는 것.","biz"],
  ["개념 증명","Proof of Concept (PoC)","아이디어의 실현 가능성을 작게 검증하는 시범 프로젝트.","biz"],
  ["투자수익률","Return on Investment (ROI)","투자 대비 얻은 이익의 비율.","biz"],
  ["예측 분석","Predictive Analytics","데이터를 활용해 미래의 결과를 예측하는 분석.","biz"],
  ["초개인화","Hyper-personalization","개인별 맥락까지 반영해 맞춤형 경험을 제공하는 것.","biz"],
  ["로봇 프로세스 자동화","Robotic Process Automation (RPA)","반복적인 업무를 소프트웨어 로봇으로 자동화하는 기술.","biz"],
  ["데이터 거버넌스","Data Governance","데이터의 품질·보안·활용을 관리하는 체계.","biz"],
  ["책임 있는 AI","Responsible AI","안전하고 공정하며 투명하게 AI를 개발·운영하려는 원칙.","biz"],
  ["차등 프라이버시","Differential Privacy","개인 정보를 보호하면서 데이터를 분석하는 기법.","biz"],
];
