const EXAMPLES = [
  ["We're integrating AI across all our customer-facing products this quarter.","이번 분기에 모든 고객 대면 제품에 AI를 통합하고 있습니다.","What's our AI adoption roadmap for next year?","내년 AI 도입 로드맵은 어떻게 되나요?"],
  ["Our machine learning models improved forecasting accuracy by 30%.","저희 머신러닝 모델이 예측 정확도를 30% 개선했습니다.","How long does it take to train a new machine learning model?","새 머신러닝 모델을 학습시키는 데 얼마나 걸리나요?"],
  ["Deep learning has been crucial for our image recognition product.","딥러닝은 저희 이미지 인식 제품에 핵심적이었습니다.","Do we have the GPU capacity to run deep learning at scale?","딥러닝을 대규모로 돌릴 GPU 용량은 충분한가요?"],
  ["We need to optimize this algorithm — it's the bottleneck.","이 알고리즘을 최적화해야 합니다. 병목이에요.","Which algorithm gave you the best results?","어떤 알고리즘이 가장 좋은 결과를 냈나요?"],
  ["Our biggest competitive advantage is the volume of data we've collected.","우리의 가장 큰 경쟁 우위는 우리가 수집한 데이터의 양입니다.","Is our data clean enough for production use?","우리 데이터가 운영에 쓸 만큼 깨끗한가요?"],
  ["Handling big data at this scale requires different infrastructure.","이 규모의 빅데이터를 다루려면 다른 인프라가 필요합니다.","What's our big data storage strategy looking like?","우리 빅데이터 저장 전략은 어떻게 되어 있나요?"],
  ["Training the new model took about two weeks on our cluster.","새 모델 학습에 저희 클러스터로 약 2주 걸렸습니다.","What's the cost of training a model this size?","이 크기의 모델을 학습시키는 비용이 얼마인가요?"],
  ["We've deployed three different models to compare performance.","성능 비교를 위해 세 가지 모델을 배포했습니다.","When was this model last retrained?","이 모델은 마지막으로 언제 재학습되었나요?"],
  ["Adding seasonality as a feature significantly improved predictions.","계절성을 피처로 추가하니 예측이 크게 개선됐습니다.","Which features are driving most of the model's decisions?","어떤 피처들이 모델 결정의 대부분을 좌우하나요?"],
  ["We're running with about 7 billion parameters in this version.","이번 버전은 약 70억 개의 파라미터로 돌리고 있습니다.","Do we need this many parameters, or can we go smaller?","이렇게 많은 파라미터가 필요한가요, 더 작게 가도 되나요?"],
  ["For this use case, supervised learning is the right approach.","이 사용 사례에는 지도 학습이 맞는 접근법입니다.","Do we have enough labeled data for supervised learning?","지도 학습에 충분한 라벨링 데이터가 있나요?"],
  ["We used unsupervised learning to discover customer segments.","고객 세그먼트를 발견하기 위해 비지도 학습을 사용했습니다.","Could unsupervised learning help us find patterns we're missing?","비지도 학습이 우리가 놓치는 패턴을 찾는 데 도움이 될까요?"],
  ["The neural network architecture we chose is industry-standard.","저희가 선택한 신경망 아키텍처는 업계 표준입니다.","How interpretable are decisions from this neural network?","이 신경망의 결정을 얼마나 해석할 수 있나요?"],
  ["Our deep neural network showed a meaningful accuracy lift.","저희 심층 신경망이 의미 있는 정확도 향상을 보였습니다.","What's the latency on inference with that deep neural network?","그 심층 신경망의 추론 지연 시간은 얼마인가요?"],
  ["Each node in this layer learns a different pattern.","이 층의 각 노드는 다른 패턴을 학습합니다.","How many neurons do we need to capture the complexity?","그 복잡도를 잡으려면 뉴런이 몇 개나 필요한가요?"],
  ["Adding two more layers gave us a 5% accuracy boost.","두 층 더 추가하니 정확도가 5% 올라갔습니다.","Could we cut some layers to reduce inference time?","추론 시간을 줄이려고 일부 레이어를 잘라낼 수 있을까요?"],
  ["Switching to a different activation function stabilized training.","다른 활성화 함수로 바꾸니 학습이 안정됐습니다.","Why did you pick ReLU over other activation functions?","다른 활성화 함수 대신 ReLU를 선택한 이유가 뭔가요?"],
  ["These weights were initialized randomly and tuned over training.","이 가중치는 무작위로 초기화되어 학습 중에 튜닝됐습니다.","Should we save the trained weights for reuse?","학습된 가중치를 재사용을 위해 저장해 둘까요?"],
  ["The bias term lets the model fit a wider range of patterns.","편향 항은 모델이 더 넓은 범위의 패턴에 맞을 수 있게 합니다.","Are we measuring bias separately from overall error?","편향을 전체 오차와 별도로 측정하고 있나요?"],
  ["We trained for 50 epochs before performance plateaued.","성능이 평탄해지기 전까지 50 에포크를 학습시켰습니다.","How do we decide when to stop adding more epochs?","에포크를 더 추가하는 걸 언제 멈출지 어떻게 결정하나요?"],
  ["Reducing the batch size helped with memory usage.","배치 사이즈를 줄이니 메모리 사용에 도움이 됐습니다.","What's the optimal batch size for our hardware?","저희 하드웨어에 최적인 배치 사이즈는 얼마인가요?"],
  ["Each iteration takes about three seconds on this setup.","이 설정에서 각 이터레이션은 약 3초 걸립니다.","How many iterations until the model converges?","모델이 수렴하기까지 몇 이터레이션이나 걸리나요?"],
  ["We chose a custom loss function to penalize false negatives more.","거짓 음성에 더 큰 페널티를 주려고 커스텀 손실 함수를 선택했습니다.","Could a different loss function align better with our business KPI?","다른 손실 함수가 우리 사업 KPI에 더 잘 맞을 수 있을까요?"],
  ["Switching from SGD to Adam optimizer cut training time in half.","SGD에서 Adam 옵티마이저로 바꾸니 학습 시간이 반으로 줄었습니다.","Which optimizer do you recommend for this kind of model?","이런 종류의 모델에는 어떤 옵티마이저를 추천하시나요?"],
  ["Gradient descent is converging, but slowly with this dataset.","경사 하강법이 수렴은 하는데, 이 데이터셋에선 느립니다.","Are we using vanilla gradient descent or a momentum variant?","기본 경사 하강법을 쓰나요, 모멘텀 변형을 쓰나요?"],
  ["We lowered the learning rate halfway through to fine-tune.","미세 조정을 위해 학습 중간에 학습률을 낮췄습니다.","What learning rate schedule are you using?","어떤 학습률 스케줄을 사용하고 있나요?"],
  ["We saw clear signs of overfitting after the 30th epoch.","30번째 에포크 이후 명확한 과적합 신호가 보였습니다.","How are we guarding against overfitting in production?","운영 환경에서 과적합을 어떻게 방지하고 있나요?"],
  ["The model is underfitting — it can't even nail the training data.","모델이 과소적합입니다. 학습 데이터조차 못 맞춰요.","Is the model underfitting because it's too small for the task?","작업에 비해 모델이 너무 작아서 과소적합인 건가요?"],
  ["Our validation set was carefully sampled to mirror production.","검증 세트는 운영 환경을 반영하도록 신중히 샘플링했습니다.","How big is the validation set relative to training data?","학습 데이터 대비 검증 세트는 얼마나 큰가요?"],
  ["On the test set, the model hit 92% accuracy.","테스트 세트에서 모델은 92% 정확도를 기록했습니다.","Has anyone seen the test set during model selection?","모델 선정 과정에서 누가 테스트 세트를 본 적이 있나요?"],
  ["We hit 95% accuracy on the holdout set this iteration.","이번 이터레이션에서 홀드아웃 세트에 대해 95% 정확도를 달성했습니다.","Is accuracy the right metric, given the class imbalance?","클래스 불균형을 고려하면 정확도가 맞는 지표인가요?"],
  ["Our precision improved, but recall dropped — that's the tradeoff.","정밀도는 개선됐지만 재현율은 떨어졌습니다 — 트레이드오프죠.","What's the current precision on positive predictions?","양성 예측의 현재 정밀도는 얼마인가요?"],
  ["For fraud detection, we'd rather optimize for recall.","사기 탐지에서는 재현율을 최적화하는 게 낫습니다.","Can we trade some precision for higher recall here?","여기선 정밀도를 좀 희생해서 재현율을 높일 수 있을까요?"],
  ["Our F1 score on the test set was 0.87.","테스트 세트에서 F1 점수는 0.87이었습니다.","Should we be optimizing for F1 or weighted F1?","F1을 최적화해야 하나요, 가중 F1을 최적화해야 하나요?"],
  ["Looking at the confusion matrix, most errors are in one category.","혼동 행렬을 보면 대부분의 오류가 한 카테고리에 몰려 있습니다.","Can you walk me through the confusion matrix?","혼동 행렬을 좀 설명해 주실 수 있나요?"],
  ["The ROC curve shows the model is clearly above baseline.","ROC 곡선은 모델이 기준선보다 확실히 위에 있음을 보여줍니다.","What does the ROC curve look like at the operating threshold?","운영 임계값에서 ROC 곡선이 어떻게 보이나요?"],
  ["We achieved an AUC of 0.94 on the validation set.","검증 세트에서 AUC 0.94를 달성했습니다.","Is AUC alone enough, or do we need calibration metrics too?","AUC만으로 충분한가요, 캘리브레이션 지표도 필요한가요?"],
  ["We're balancing the bias-variance tradeoff with regularization.","정칙화로 편향-분산 트레이드오프를 조절하고 있습니다.","Where do you think we are on the bias-variance tradeoff?","편향-분산 트레이드오프에서 우리는 어디쯤이라고 보시나요?"],
  ["Data preprocessing actually takes more time than model training.","데이터 전처리가 모델 학습보다 시간이 더 많이 걸립니다.","Can we automate more of the data preprocessing steps?","데이터 전처리 단계를 더 자동화할 수 있을까요?"],
  ["After data cleaning, we removed roughly 12% of the records.","데이터 정제 후 약 12%의 레코드를 제거했습니다.","What's our data cleaning policy for missing values?","결측값에 대한 데이터 정제 정책은 어떻게 됩니까?"],
  ["Feature scaling was essential — the model wouldn't converge without it.","특징 스케일링이 필수였습니다. 안 하면 모델이 수렴하지 않아요.","Did you apply feature scaling consistently across train and test?","학습과 테스트에 특징 스케일링을 일관되게 적용했나요?"],
  ["We applied min-max normalization to all numeric features.","모든 수치 피처에 최소-최대 정규화를 적용했습니다.","Should we normalize per batch or globally?","배치별로 정규화해야 하나요, 전역으로 해야 하나요?"],
  ["Standardization brought all features to the same scale.","표준화로 모든 피처를 같은 스케일로 맞췄습니다.","Do we need standardization if the model is tree-based?","트리 기반 모델이라면 표준화가 필요한가요?"],
  ["We used one-hot encoding for the categorical fields.","범주형 필드에 원-핫 인코딩을 사용했습니다.","Could one-hot encoding blow up dimensionality here?","여기서 원-핫 인코딩이 차원을 폭증시킬 수 있지 않나요?"],
  ["Our NLP pipeline now handles five languages.","저희 NLP 파이프라인이 이제 5개 언어를 처리합니다.","What NLP tasks would give us the most business value?","어떤 NLP 작업이 우리에게 가장 큰 사업적 가치를 줄까요?"],
  ["Text classification is automatically routing support tickets now.","텍스트 분류가 이제 지원 티켓을 자동으로 배정하고 있습니다.","How accurate is the text classification compared to humans?","텍스트 분류가 사람과 비교해 얼마나 정확한가요?"],
  ["Sentiment analysis on customer reviews showed a clear shift this month.","고객 리뷰 감성 분석에서 이번 달 명확한 변화가 보였습니다.","Is sentiment analysis reliable for sarcastic comments?","감성 분석이 반어법이 섞인 댓글에도 신뢰할 만한가요?"],
  ["Named entity recognition extracts companies and people from contracts.","개체명 인식이 계약서에서 회사명과 인명을 추출합니다.","Can named entity recognition handle Korean names well?","개체명 인식이 한국 인명을 잘 처리할 수 있나요?"],
  ["Machine translation quality has improved dramatically in recent years.","기계 번역 품질이 최근 몇 년간 극적으로 향상됐습니다.","Do we still need human review for machine translation output?","기계 번역 결과에 여전히 사람의 검수가 필요한가요?"],
  ["Our chatbot deflects about 40% of incoming customer queries.","저희 챗봇이 들어오는 고객 문의의 약 40%를 처리합니다.","How easy is it to update the chatbot's knowledge base?","챗봇의 지식 베이스를 업데이트하기가 얼마나 쉽나요?"],
  ["Speech recognition accuracy in noisy environments is still a challenge.","시끄러운 환경에서의 음성 인식 정확도는 여전히 과제입니다.","Does the speech recognition model support multiple accents?","음성 인식 모델이 여러 액센트를 지원하나요?"],
  ["Our new text-to-speech voice sounds nearly indistinguishable from human.","저희 새 TTS 음성은 사람과 거의 구분이 안 됩니다.","Can text-to-speech generate samples in real time?","TTS가 실시간으로 샘플을 생성할 수 있나요?"],
  ["Computer vision is the foundation of our quality inspection system.","컴퓨터 비전이 저희 품질 검사 시스템의 기반입니다.","What's the throughput of our computer vision pipeline?","우리 컴퓨터 비전 파이프라인의 처리량은 얼마인가요?"],
  ["Image classification achieves 99% on the standard benchmark.","이미지 분류가 표준 벤치마크에서 99%를 달성합니다.","How does image classification handle edge cases?","이미지 분류가 예외 사례를 어떻게 처리하나요?"],
  ["Object detection runs at 30 frames per second on our hardware.","객체 감지가 저희 하드웨어에서 초당 30프레임으로 돕니다.","Can object detection identify multiple objects at once?","객체 감지가 동시에 여러 객체를 식별할 수 있나요?"],
  ["Image segmentation gives us pixel-level precision for medical imaging.","이미지 분할은 의료 영상에 픽셀 단위의 정밀도를 제공합니다.","Is image segmentation overkill for our use case?","우리 사용 사례에 이미지 분할은 과한가요?"],
  ["We're exploring GANs for synthetic data generation.","합성 데이터 생성을 위해 GAN을 검토하고 있습니다.","Are GANs stable enough for production use?","GAN이 운영에 쓸 만큼 안정적인가요?"],
  ["Reinforcement learning powers our dynamic pricing engine.","강화 학습이 저희 동적 가격 책정 엔진을 구동합니다.","How long does reinforcement learning take to converge in practice?","강화 학습이 실제로 수렴하기까지 얼마나 걸리나요?"],
  ["Each agent learns its policy independently before we combine them.","각 에이전트는 결합 전에 독립적으로 정책을 학습합니다.","How do agents coordinate in multi-agent environments?","에이전트들이 다중 에이전트 환경에서 어떻게 협력하나요?"],
  ["We built a custom simulation environment for training.","학습을 위해 커스텀 시뮬레이션 환경을 구축했습니다.","Can we test the agent in a sandbox environment first?","에이전트를 먼저 샌드박스 환경에서 테스트할 수 있을까요?"],
  ["The state space is much larger than we initially modeled.","상태 공간이 우리가 처음 모델링한 것보다 훨씬 큽니다.","How are we representing the state efficiently?","상태를 어떻게 효율적으로 표현하고 있나요?"],
  ["We restricted the action space to keep training tractable.","학습을 다루기 쉽게 하려고 액션 공간을 제한했습니다.","What's the size of our action space?","우리 액션 공간의 크기는 얼마인가요?"],
  ["Designing the reward function was the hardest part of this project.","보상 함수 설계가 이 프로젝트에서 가장 어려운 부분이었습니다.","Could the reward signal be incentivizing the wrong behavior?","보상 신호가 잘못된 행동을 부추기고 있을 가능성은 없나요?"],
  ["The learned policy outperforms our hand-crafted rules by 18%.","학습된 정책이 수작업 규칙보다 18% 더 잘 합니다.","Is the policy interpretable, or do we just trust the output?","정책이 해석 가능한가요, 결과만 믿어야 하나요?"],
  ["The value function estimates long-term returns from each state.","가치 함수가 각 상태에서의 장기적 보상을 추정합니다.","How do we validate the value function estimates?","가치 함수 추정치를 어떻게 검증하나요?"],
  ["Q-learning worked well for our discrete-action problem.","Q-러닝이 이산 액션 문제에 잘 맞았습니다.","Does Q-learning scale to our larger state space?","Q-러닝이 더 큰 상태 공간으로 확장되나요?"],
  ["We migrated from tabular Q-learning to DQN for better generalization.","일반화 향상을 위해 표 기반 Q-러닝에서 DQN으로 옮겼습니다.","How much GPU time does training a DQN typically require?","DQN 학습에 GPU 시간이 보통 얼마나 필요한가요?"],
  ["Transfer learning let us hit good accuracy with very little data.","전이 학습 덕분에 매우 적은 데이터로 좋은 정확도에 도달했습니다.","Which pretrained model are we using as the base for transfer learning?","전이 학습의 기반으로 어떤 사전학습 모델을 쓰고 있나요?"],
  ["We're fine-tuning the base model on our domain-specific data.","도메인 특화 데이터로 베이스 모델을 미세 조정하고 있습니다.","How long does fine-tuning take compared to training from scratch?","처음부터 학습하는 것과 비교해 미세 조정에 얼마나 걸리나요?"],
  ["Ensemble learning gave us the final 2% accuracy gain we needed.","앙상블 학습이 우리가 필요했던 마지막 2% 정확도 향상을 줬습니다.","Is the latency cost of ensemble learning worth it in production?","운영에서 앙상블 학습의 지연 비용을 감수할 만한가요?"],
  ["Bagging reduced variance noticeably on our model.","배깅이 저희 모델의 분산을 눈에 띄게 줄였습니다.","Are we using bagging or boosting for the ensemble?","앙상블에 배깅을 쓰고 있나요, 부스팅을 쓰고 있나요?"],
  ["Boosting consistently beat single models on our tabular data.","부스팅이 저희 표 형식 데이터에서 단일 모델을 꾸준히 이겼습니다.","How prone is boosting to overfitting in our case?","우리 경우 부스팅이 과적합에 얼마나 취약한가요?"],
  ["Gradient boosting is still our go-to for structured tabular data.","그래디언트 부스팅은 여전히 구조화된 표 데이터에 대한 우리의 우선 선택입니다.","Did you try gradient boosting before going to deep learning?","딥러닝으로 가기 전에 그래디언트 부스팅을 시도해 봤나요?"],
  ["XGBoost is fast, accurate, and easy to deploy — hard to beat.","XGBoost는 빠르고 정확하고 배포하기 쉬워서 이기기 어렵습니다.","Why did you choose XGBoost over LightGBM?","LightGBM 대신 XGBoost를 선택한 이유가 뭔가요?"],
  ["Data mining surfaced three customer segments we hadn't noticed.","데이터 마이닝으로 저희가 인식 못 하던 고객 세그먼트 셋을 발견했습니다.","What data mining tools is your team using right now?","팀에서 지금 어떤 데이터 마이닝 도구를 쓰고 있나요?"],
  ["Clustering revealed natural groupings in user behavior.","군집화로 사용자 행동의 자연스러운 그룹이 드러났습니다.","How did you decide on the number of clusters?","군집의 개수를 어떻게 결정했나요?"],
  ["Our anomaly detection system catches roughly 80% of fraud attempts.","저희 이상 감지 시스템이 사기 시도의 약 80%를 잡아냅니다.","What's the false-positive rate on anomaly detection?","이상 감지의 거짓 양성률은 얼마인가요?"],
  ["The recommendation system drives 35% of our total sales.","추천 시스템이 전체 매출의 35%를 견인합니다.","How often do we retrain the recommendation system?","추천 시스템을 얼마나 자주 재학습시키나요?"],
  ["A/B testing confirmed the new model lifts conversion by 4%.","A/B 테스팅으로 새 모델이 전환율을 4% 올린다는 게 확인됐습니다.","How long should we run the A/B test for statistical significance?","통계적 유의성을 위해 A/B 테스트를 얼마나 돌려야 하나요?"],
  ["Cloud computing gives us elasticity we couldn't have on-prem.","클라우드 컴퓨팅은 온프레미스로는 못 가질 탄력성을 줍니다.","What's our monthly cloud computing bill trending toward?","월간 클라우드 컴퓨팅 비용이 어디로 향하고 있나요?"],
  ["We provisioned 16 GPUs for this training run.","이번 학습에는 GPU 16개를 할당했습니다.","Do we have enough GPU capacity for next quarter?","다음 분기 GPU 용량이 충분한가요?"],
  ["Moving training to TPUs cut our cost per epoch by 40%.","학습을 TPU로 옮기니 에포크당 비용이 40% 줄었습니다.","Is TPU compatibility a blocker for our current framework?","TPU 호환성이 현재 프레임워크에 걸림돌인가요?"],
  ["Edge computing is critical for low-latency use cases.","엣지 컴퓨팅은 저지연 사용 사례에 매우 중요합니다.","Can we deploy this model on edge devices?","이 모델을 엣지 디바이스에 배포할 수 있을까요?"],
  ["We expose all model functionality through a clean REST API.","모든 모델 기능을 깔끔한 REST API로 노출합니다.","Is the API documented well enough for partner integration?","파트너 통합을 위해 API 문서화가 충분한가요?"],
  ["Our SDK supports Python, Java, and JavaScript out of the box.","저희 SDK는 기본적으로 Python, Java, JavaScript를 지원합니다.","What's the upgrade story for older SDK versions?","이전 SDK 버전의 업그레이드 시나리오는 어떻게 되나요?"],
  ["Most of our stack is open source, which keeps licensing costs down.","스택 대부분이 오픈소스라서 라이선스 비용이 낮습니다.","Are there open source alternatives to this commercial tool?","이 상용 도구에 오픈소스 대안이 있나요?"],
  ["We standardized on one framework to reduce maintenance burden.","유지보수 부담을 줄이려고 하나의 프레임워크로 표준화했습니다.","Why did you pick this framework over the alternatives?","대안들 대신 이 프레임워크를 선택한 이유가 뭔가요?"],
  ["Our production models are mostly built in TensorFlow.","저희 운영 모델은 대부분 TensorFlow로 만들어졌습니다.","Is the team comfortable maintaining a TensorFlow stack?","팀이 TensorFlow 스택을 유지보수하는 데 익숙한가요?"],
  ["Research moves faster in PyTorch — that's why we use it.","PyTorch에서 연구가 더 빨라서 그걸 씁니다.","Could we migrate from PyTorch to something else if needed?","필요하면 PyTorch에서 다른 걸로 옮길 수 있나요?"],
  ["Keras lets junior engineers prototype models in a day.","Keras 덕분에 주니어 엔지니어가 하루 만에 모델을 프로토타입합니다.","Is Keras still actively maintained?","Keras가 아직 활발히 유지보수되고 있나요?"],
  ["Scikit-learn covers about 80% of our classical ML needs.","scikit-learn이 저희 고전 ML 요구의 약 80%를 커버합니다.","Can scikit-learn handle our dataset size?","scikit-learn이 우리 데이터셋 크기를 처리할 수 있나요?"],
  ["All our exploratory work happens in Jupyter notebooks.","모든 탐색 작업은 주피터 노트북에서 이뤄집니다.","Do we have a process for promoting notebooks to production code?","노트북을 운영 코드로 승격시키는 프로세스가 있나요?"],
  ["Deployment used to take a week, now it's a few hours.","배포가 예전엔 일주일 걸렸는데 지금은 몇 시간입니다.","What's our rollback plan if deployment goes wrong?","배포가 잘못되면 롤백 계획이 어떻게 되나요?"],
  ["Scalability was a core design consideration from day one.","확장성은 첫날부터 핵심 설계 고려사항이었습니다.","What's the scalability ceiling on the current architecture?","현재 아키텍처의 확장성 한계는 어디인가요?"],
  ["Explainable AI is a regulatory requirement in our industry.","설명 가능한 AI는 우리 업계의 규제 요구사항입니다.","How do we explain a deep learning model to non-technical stakeholders?","비기술 이해관계자에게 딥러닝 모델을 어떻게 설명하나요?"],
  ["We audit our models quarterly for fairness across demographic groups.","인구 통계 그룹 전반의 공정성을 위해 분기별로 모델을 감사합니다.","What fairness metrics are we tracking?","어떤 공정성 지표를 추적하고 있나요?"],
  ["We have an AI ethics board that reviews every major release.","주요 릴리스마다 검토하는 AI 윤리 위원회가 있습니다.","Do we have written ethics guidelines for AI development?","AI 개발에 대한 명문화된 윤리 가이드라인이 있나요?"],
  ["We're evaluating which large language model to license for our chatbot.","챗봇에 라이선스할 LLM을 평가하고 있습니다.","What's the total cost of ownership for a large language model at scale?","대규모로 LLM을 운영하는 총 소유 비용이 얼마인가요?"],
  ["We're building on top of a foundation model rather than training from scratch.","처음부터 학습하지 않고 파운데이션 모델 위에 구축하고 있습니다.","Which foundation model gives us the best price-performance ratio?","어떤 파운데이션 모델이 가장 좋은 가성비를 줍니까?"],
  ["The transformer architecture has become the default for sequence tasks.","트랜스포머 아키텍처가 시퀀스 작업의 기본이 됐습니다.","How does the transformer compare to RNNs for our use case?","우리 사용 사례에서 트랜스포머가 RNN과 비교해 어떤가요?"],
  ["The attention mechanism is what lets these models capture long-range context.","어텐션 메커니즘 덕분에 이 모델들이 긴 맥락을 잡을 수 있습니다.","Can we visualize what the attention mechanism is focusing on?","어텐션 메커니즘이 무엇에 집중하는지 시각화할 수 있나요?"],
  ["Each API call costs us about 500 tokens on average.","각 API 호출당 평균 500토큰 정도 듭니다.","How are tokens being counted for billing purposes?","토큰이 과금 목적으로 어떻게 계산되나요?"],
  ["The tokenizer handles Korean and English with the same efficiency.","토크나이저가 한국어와 영어를 동일한 효율로 처리합니다.","Does the tokenizer split Korean correctly?","토크나이저가 한국어를 제대로 분리하나요?"],
  ["Embeddings let us measure semantic similarity across documents.","임베딩으로 문서 전반의 의미적 유사도를 측정할 수 있습니다.","Where are we storing the embeddings, and how big is the index?","임베딩을 어디에 저장하고 있고, 인덱스 크기가 얼마인가요?"],
  ["A well-crafted prompt can outperform a fine-tuned model.","잘 짠 프롬프트가 미세 조정된 모델보다 잘 할 수 있습니다.","Can you share the prompt template you're using?","사용 중인 프롬프트 템플릿을 공유해 주실 수 있나요?"],
  ["Our prompt engineering team improved response quality by 25%.","프롬프트 엔지니어링 팀이 응답 품질을 25% 개선했습니다.","Is prompt engineering scalable, or do we need fine-tuning eventually?","프롬프트 엔지니어링이 확장 가능한가요, 결국 미세 조정이 필요한가요?"],
  ["We had to chunk the document because it exceeded the context window.","문서가 컨텍스트 윈도우를 초과해서 청크로 잘라야 했습니다.","What's the context window limit on the model we're using?","저희가 쓰는 모델의 컨텍스트 윈도우 한계는 얼마인가요?"],
  ["Hallucination remains the biggest barrier to enterprise adoption.","환각이 여전히 기업 도입의 가장 큰 장벽입니다.","How are we detecting and reducing hallucinations?","환각을 어떻게 탐지하고 줄이고 있나요?"],
  ["RAG significantly reduced hallucinations on factual queries.","RAG가 사실 질문에 대한 환각을 크게 줄였습니다.","Would RAG help us ground responses in our internal documents?","RAG가 응답을 우리 내부 문서에 근거하게 하는 데 도움이 될까요?"],
  ["We selected a vector database that scales to 100 million embeddings.","1억 임베딩까지 확장되는 벡터 데이터베이스를 선택했습니다.","What's the query latency on the vector database under load?","부하 상태에서 벡터 데이터베이스의 쿼리 지연 시간은 얼마인가요?"],
  ["Semantic search dramatically improved internal knowledge discovery.","시맨틱 검색이 내부 지식 발견을 극적으로 개선했습니다.","How does semantic search compare to traditional keyword search on relevance?","시맨틱 검색이 전통 키워드 검색과 비교해 관련성이 어떤가요?"],
  ["Modern LLMs do zero-shot learning remarkably well.","현대 LLM은 제로샷 학습을 놀랍게 잘 합니다.","Can we rely on zero-shot learning for production, or do we need examples?","운영에서 제로샷 학습에 의존할 수 있을까요, 예시가 필요할까요?"],
  ["We provide just three examples and the model handles the task with few-shot learning.","예시 세 개만 제공하면 모델이 퓨샷 학습으로 작업을 처리합니다.","How many examples typically work best for few-shot learning?","퓨샷 학습에 보통 예시 몇 개가 가장 잘 통하나요?"],
  ["In-context learning lets us adapt the model without any training.","인컨텍스트 러닝으로 학습 없이 모델을 적응시킬 수 있습니다.","Does in-context learning persist across sessions, or only within one prompt?","인컨텍스트 러닝이 세션 간에 유지되나요, 한 프롬프트 내에서만 적용되나요?"],
  ["RLHF is how we aligned the model with our brand voice.","RLHF로 모델을 우리 브랜드 어조에 맞췄습니다.","How many human-feedback samples did RLHF require?","RLHF에 사람 피드백 샘플이 얼마나 필요했나요?"],
  ["Model alignment is critical when the AI faces customers directly.","AI가 고객을 직접 대할 때 모델 정렬이 매우 중요합니다.","What's our alignment evaluation process before each release?","각 릴리스 전 정렬 평가 프로세스는 어떻게 되나요?"],
  ["Multimodal models open up brand new product categories for us.","멀티모달 모델은 우리에게 완전히 새로운 제품 카테고리를 열어줍니다.","How much more expensive is multimodal inference compared to text-only?","텍스트 전용과 비교해 멀티모달 추론이 얼마나 더 비싼가요?"],
  ["Diffusion models now produce marketing visuals indistinguishable from photography.","디퓨전 모델이 이제 사진과 구분이 안 되는 마케팅 비주얼을 만듭니다.","Are diffusion models fast enough for real-time use?","디퓨전 모델이 실시간 사용에 충분히 빠른가요?"],
  ["Inference costs are now larger than training costs for us.","저희는 이제 추론 비용이 학습 비용보다 큽니다.","How are we optimizing inference latency in production?","운영에서 추론 지연 시간을 어떻게 최적화하고 있나요?"],
  ["Quantization cut model size by 4x with minimal accuracy loss.","양자화로 정확도 손실을 최소화하면서 모델 크기를 4배 줄였습니다.","Did quantization affect accuracy on edge cases?","양자화가 예외 사례 정확도에 영향을 줬나요?"],
  ["Knowledge distillation lets a small model behave like a large one.","지식 증류로 작은 모델이 큰 모델처럼 동작할 수 있습니다.","How much accuracy do we lose with knowledge distillation?","지식 증류로 정확도를 얼마나 잃나요?"],
  ["AI agents are starting to handle multi-step workflows autonomously.","AI 에이전트가 다단계 워크플로우를 자율적으로 처리하기 시작했습니다.","What tools should our AI agent have access to?","AI 에이전트가 어떤 도구에 접근할 수 있어야 하나요?"],
  ["This regression model predicts demand within a 5% error margin.","이 회귀 모델이 5% 오차 범위 내에서 수요를 예측합니다.","Is regression the right framing, or should this be classification?","회귀로 잡는 게 맞나요, 분류 문제로 봐야 하나요?"],
  ["We framed this as a multi-class classification problem.","이걸 다중 클래스 분류 문제로 정의했습니다.","How balanced are the classes in our classification dataset?","분류 데이터셋의 클래스가 얼마나 균형 잡혀 있나요?"],
  ["Linear regression remains a strong baseline for many business problems.","선형 회귀는 여전히 많은 비즈니스 문제에 강력한 베이스라인입니다.","Did you start with linear regression before trying more complex models?","더 복잡한 모델을 시도하기 전에 선형 회귀부터 시작했나요?"],
  ["Logistic regression is interpretable and good enough for this task.","로지스틱 회귀는 해석 가능하고 이 작업에 충분히 좋습니다.","What's the AUC on the logistic regression baseline?","로지스틱 회귀 베이스라인의 AUC는 얼마인가요?"],
  ["Decision trees give us rules we can show to auditors.","의사결정 나무는 감사관에게 보여줄 수 있는 규칙을 제공합니다.","How deep should we let the decision tree grow?","의사결정 나무를 얼마나 깊게 키워야 하나요?"],
  ["Random forest is robust and works well out of the box.","랜덤 포레스트는 견고하고 기본 설정으로도 잘 동작합니다.","Why did you choose random forest over gradient boosting?","그래디언트 부스팅 대신 랜덤 포레스트를 선택한 이유가 뭔가요?"],
  ["SVM was the standard before deep learning for many vision tasks.","SVM은 많은 비전 작업에서 딥러닝 이전의 표준이었습니다.","Does SVM scale to our dataset size?","SVM이 우리 데이터셋 크기로 확장되나요?"],
  ["k-NN is a simple baseline but expensive at query time.","k-NN은 단순한 베이스라인이지만 쿼리 시 비쌉니다.","What value of k did you choose, and why?","k 값을 얼마로 정했고, 이유가 뭔가요?"],
  ["K-means clustering surfaced five distinct customer personas.","k-평균 군집화로 다섯 가지 뚜렷한 고객 페르소나가 드러났습니다.","How did you pick the number of clusters for k-means?","k-평균에서 군집 개수를 어떻게 선택했나요?"],
  ["Naive Bayes is fast and surprisingly effective for spam filtering.","나이브 베이즈는 빠르고 스팸 필터링에 의외로 효과적입니다.","Is the naive independence assumption hurting us here?","나이브한 독립 가정이 여기서 우리에게 해가 되고 있나요?"],
  ["Dimensionality reduction made the model trainable on our laptops.","차원 축소 덕분에 노트북에서도 모델을 학습시킬 수 있었습니다.","How much information are we losing through dimensionality reduction?","차원 축소로 정보를 얼마나 잃고 있나요?"],
  ["PCA captured 95% of the variance with just 20 components.","PCA로 단 20개 성분으로 분산의 95%를 잡아냈습니다.","Is PCA appropriate when our features aren't linearly correlated?","피처가 선형 상관이 아닐 때 PCA가 적절한가요?"],
  ["Hyperparameter tuning took longer than the actual training.","하이퍼파라미터 튜닝이 실제 학습보다 오래 걸렸습니다.","Are we using grid search or Bayesian optimization for hyperparameters?","하이퍼파라미터에 그리드 서치를 쓰나요, 베이지안 최적화를 쓰나요?"],
  ["We used 5-fold cross-validation to get a reliable accuracy estimate.","신뢰할 만한 정확도 추정치를 얻기 위해 5겹 교차 검증을 썼습니다.","Should we be doing time-series cross-validation given our data?","우리 데이터를 고려하면 시계열 교차 검증을 해야 하지 않나요?"],
  ["We added L2 regularization to prevent overfitting.","과적합 방지를 위해 L2 정칙화를 추가했습니다.","What regularization strength did you settle on?","어떤 정칙화 강도로 정했나요?"],
  ["Dropout at 30% gave the best generalization in our tests.","30% 드롭아웃이 저희 테스트에서 가장 좋은 일반화를 보였습니다.","Is dropout the right regularizer for this architecture?","이 아키텍처에 드롭아웃이 맞는 정칙화인가요?"],
  ["Batch normalization let us use much higher learning rates.","배치 정규화 덕분에 훨씬 높은 학습률을 쓸 수 있었습니다.","Do we need batch normalization in every layer?","모든 층에 배치 정규화가 필요한가요?"],
  ["The vanishing gradient problem killed early attempts at deep networks.","그래디언트 소실 문제가 초기 깊은 신경망 시도들을 무산시켰습니다.","How does this architecture avoid the vanishing gradient problem?","이 아키텍처는 그래디언트 소실 문제를 어떻게 피하나요?"],
  ["CNNs are still the workhorse for production vision systems.","CNN은 여전히 운영 비전 시스템의 주력입니다.","Are we using a CNN or shifting to vision transformers?","CNN을 쓰고 있나요, 비전 트랜스포머로 옮기고 있나요?"],
  ["Most of our sequence work moved from RNNs to transformers.","저희 시퀀스 작업 대부분이 RNN에서 트랜스포머로 옮겨갔습니다.","Are there cases where an RNN still beats a transformer?","RNN이 아직 트랜스포머를 이기는 경우가 있나요?"],
  ["Investing in MLOps cut our deployment cycle from weeks to hours.","MLOps에 투자했더니 배포 주기가 몇 주에서 몇 시간으로 줄었습니다.","What's the maturity of our current MLOps stack?","현재 우리 MLOps 스택의 성숙도가 어느 수준인가요?"],
  ["We detected model drift after a marketing campaign changed user behavior.","마케팅 캠페인으로 사용자 행동이 바뀐 뒤 모델 드리프트를 감지했습니다.","How often are we checking for model drift?","모델 드리프트를 얼마나 자주 점검하나요?"],
  ["Data drift is monitored in real time on all our key features.","모든 핵심 피처에 대해 데이터 드리프트를 실시간으로 모니터링합니다.","What action do we take when data drift is detected?","데이터 드리프트가 감지되면 어떤 조치를 취하나요?"],
  ["Centralizing features in a feature store eliminated training-serving skew.","피처를 피처 스토어에 중앙화해서 학습-서빙 차이를 없앴습니다.","Who owns the feature store, data team or ML team?","피처 스토어의 소유는 데이터 팀인가요, ML 팀인가요?"],
  ["Our model serving infrastructure handles 10,000 requests per second.","저희 모델 서빙 인프라가 초당 1만 건의 요청을 처리합니다.","What's the P99 latency on model serving?","모델 서빙의 P99 지연 시간은 얼마인가요?"],
  ["The end-to-end pipeline runs nightly without any manual steps.","엔드 투 엔드 파이프라인이 수작업 없이 매일 밤 돕니다.","Where does our pipeline most frequently fail?","우리 파이프라인이 가장 자주 실패하는 지점은 어디인가요?"],
  ["Containers made it trivial to move models between environments.","컨테이너 덕분에 모델을 환경 간에 옮기는 게 간단해졌습니다.","Are all our models containerized at this point?","지금 시점에서 모든 모델이 컨테이너화되어 있나요?"],
  ["Our data lake stores roughly two petabytes of raw data.","저희 데이터 레이크에는 대략 2페타바이트의 원천 데이터가 있습니다.","How do we govern access to the data lake?","데이터 레이크의 접근 권한을 어떻게 관리하나요?"],
  ["We rebuilt the data pipeline for tenfold throughput last quarter.","지난 분기 처리량을 10배 늘리려고 데이터 파이프라인을 재구축했습니다.","What's the freshness SLA on the data pipeline?","데이터 파이프라인의 신선도 SLA는 어떻게 되나요?"],
  ["Monitoring catches most issues before customers ever notice.","모니터링이 고객이 알아채기 전에 대부분 문제를 잡아냅니다.","What's covered by our current monitoring setup?","현재 모니터링 설정으로 무엇이 커버되나요?"],
  ["Generative AI is opening up creative workflows we couldn't automate before.","생성형 AI가 예전엔 자동화할 수 없었던 창의적 워크플로우를 열어주고 있습니다.","Where does generative AI fit into our product roadmap?","생성형 AI가 우리 제품 로드맵의 어디에 들어가나요?"],
  ["AI is the next phase of our digital transformation strategy.","AI는 우리 디지털 트랜스포메이션 전략의 다음 단계입니다.","How is digital transformation measured beyond technology spend?","기술 지출 외에 디지털 트랜스포메이션을 어떻게 측정하나요?"],
  ["Let's start with a proof of concept before committing to full deployment.","전면 배포에 들어가기 전에 개념 증명부터 시작합시다.","What's the timeline and budget for the proof of concept?","개념 증명의 일정과 예산은 어떻게 됩니까?"],
  ["We're projecting a 3x return on investment within 18 months.","18개월 내 3배 ROI를 예상하고 있습니다.","How are you calculating the return on investment here?","여기서 ROI를 어떻게 계산하고 있나요?"],
  ["Predictive analytics flagged the churn risk three months early.","예측 분석이 이탈 위험을 석 달 미리 알려줬습니다.","What predictive analytics use cases are highest leverage for us?","어떤 예측 분석 사례가 우리에게 레버리지가 가장 큰가요?"],
  ["Hyper-personalization lifted email engagement by 40%.","초개인화로 이메일 참여율이 40% 올랐습니다.","How do we balance hyper-personalization with privacy concerns?","초개인화와 프라이버시 우려 사이의 균형을 어떻게 맞추나요?"],
  ["RPA saved us about 4,000 hours of manual work last year.","RPA가 작년에 약 4,000시간의 수작업을 절감했습니다.","Where does RPA leave off and AI take over?","RPA가 끝나고 AI가 시작되는 지점은 어디인가요?"],
  ["Data governance is a prerequisite for the AI projects we want to ship.","데이터 거버넌스는 저희가 출시하려는 AI 프로젝트의 전제 조건입니다.","Who's accountable for data governance in this organization?","이 조직에서 데이터 거버넌스를 누가 책임지나요?"],
  ["Responsible AI is becoming a competitive differentiator, not just a checkbox.","책임 있는 AI가 단순 체크리스트가 아니라 경쟁 차별화 요소가 되고 있습니다.","What does responsible AI look like in practice for our team?","우리 팀에 책임 있는 AI는 실제로 어떻게 보이나요?"],
  ["Differential privacy lets us share insights without exposing individuals.","차등 프라이버시 덕분에 개인을 노출하지 않고 인사이트를 공유할 수 있습니다.","Does differential privacy hurt model accuracy in practice?","차등 프라이버시가 실제로 모델 정확도에 해가 되나요?"],
];
